# Generated by Django 6.0 on 2026-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_incomingsupply_expected_date_incomingsupply_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
