# Generated by Django 6.0 on 2026-01-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='boxes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='items_per_box',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='size_spec',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supply',
            name='category',
            field=models.CharField(blank=True, choices=[('Writing Supplies', 'Writing Supplies'), ('Paper Supplies', 'Paper Supplies'), ('Filing Supplies', 'Filing Supplies'), ('Printing Supplies', 'Printing Supplies'), ('Desk Accessories', 'Desk Accessories'), ('IT Office Accessories', 'IT Office Accessories'), ('Official Forms & Stationery', 'Official Forms & Stationery'), ('Office Maintenance Supplies', 'Office Maintenance Supplies')], max_length=100),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pack', 'pack'), ('box', 'box'), ('ream', 'ream'), ('sheet', 'sheet'), ('set', 'set'), ('bottle', 'bottle'), ('roll', 'roll'), ('can', 'can')], max_length=50),
        ),
    ]
