# Generated by Django 5.2.6 on 2026-01-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_supply_boxes_count_supply_items_per_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsupply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('name', 'size_spec')},
        ),
    ]
