# Generated by Django 6.0 on 2026-01-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_alter_incomingsupply_id_alter_supply_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsupply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
