# Generated by Django 6.0 on 2026-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='attention',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='date_needed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='item_date_needed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
