# Generated by Django 6.0 on 2026-01-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_supplyrequest_attention_supplyrequest_date_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
