# Generated by Django 6.0 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_supplyrequest_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
